image:
  repository: ghcr.io/nzbgetcom/nzbget
  pullPolicy: IfNotPresent
  tag: v24.3@sha256:33f24abc2cac6f57347aeda0edd12eaa1af5c2736fa7651db815e486ba517187
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
